### ISSUE TITLE
adding spots to cities that do not exist

### ISSUE THREAD

**Issue by dcts** [mirhamasala/lw_city_guide#75]
Hey! I just tried to add "about blank" as a spot for berlin, but berlin does not exist, so i chose "bali" (since the form forced me to choose a city). But the submission doesn't even show up in bali neither.

**Comment by mirhamasala** [comment]
Hi Thomas!

Thank you for reporting this issue.

You're right that Berlin doesn't exist. I haven't added all the cities to the app yet. I'll do so today!

As for your "about blank" spot; it has actually been created.

If you go to your "Profile" (https://wagon-city-guides.herokuapp.com/dashboard), you should see that it is _pending review._

As you can see in the below screenshot, it also shows up in my dashboard. Once I publish it, your spot will be visible too.

Thank you so much for sharing a spot! I'll make sure to add it to the right city!

I'll also try to make it more clear that once you shares a spot, it isn't published immediately but pending review by an admin.

**Comment by mirhamasala** [comment]
Added! Thanks again. ☺️
