### ISSUE TITLE
trouble setting up github app (.env file) to run app locally

### ISSUE THREAD

**Issue by dcts** [mirhamasala/lw_city_guide#85]
I'm having trouble setting up an github app as documented in `.env-example`. I get the error "webhook can't be blank". ANy idea what to put there? (see screenshot): 
![Bildschirmfoto von 2020-01-03 22-07-22](https://user-images.githubusercontent.com/44790691/71749381-8e334f00-2e75-11ea-8c7b-d86d23634029.png)

**Comment by dcts** [comment]
Ok i think the issue was that the documentation in the `.env-example` was not correct. You have to register a new **OAuth App** instead of a **GitHub App**, thats how you can get the `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` to run locally on your machine (please correct me if i'm wrong). 

I updated the documentation in the .env-example file (see my [pull-request](https://github.com/mirhamasala/lw_city_guide/pull/87))

**Comment by mirhamasala** [comment]
Yes, you're correct. Instructions for the Webhook URL were missing. I kinda tricked that field and just put the projects repo, and it worked.

But I should've probably used OAuth App from the start. I'll look into this, and test it on production too.

Thank you.

**Comment by dcts** [comment]
solved, works now :)
