### ISSUE TITLE
discussion main categories

### ISSUE THREAD

**Issue by dcts** [mirhamasala/lw_city_guide#86]
Hey! Its not really an issue, i was just wondering what kind of main categories there should be. Just wanted to start a discussion. I was a bit confused by he following categories:
- **`play`**: Is it for sport activities or board games? Or parties? 
- **`stay`**: i assume all places for accomodation like hotels, good airbnbs go here, right? 

Also I was not sure where to put "About Blank", a club for techno raves in berlin. I miss the category `party`, `club` or `night club` (or something similar).

**Comment by mirhamasala** [comment]
I wanted to make the categories sounds a bit more fun than "sleep" and "party." But perhaps it's not very user friendly/clear.

**`stay`** is indeed for accommodation

**`play`** is intended for things like clubs, yeah. Maybe we can call it **`dance`**. What do you think? I can discuss it with @lozdesign too.

**Comment by dcts** [comment]
yeah i like `dance` way better than play.

**Comment by lozdesign** [comment]
I agree with dance too

**Comment by mirhamasala** [comment]
Cool! I changed `play` to `dance`.

Let me know what you think of `sleep` vs. `stay`!

**Comment by lozdesign** [comment]
sleep 😴

**Comment by mirhamasala** [comment]
Okay! Well, I assume since @dcts was already confused about it, he'll also prefer `sleep`, so I changed it already! Thanks bots. ❤️
